name: flutterhole
description: A third party Android application for the Pi-HoleÂ® dashboard.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # error handling using `Either<Failure, SuccessType>`
  dartz: ^0.9.1
  # service location
  get_it: ^4.0.2
  # dependency injection
  injectable: ^0.3.0
  # state management
  bloc: ^4.0.0
  provider: ^4.1.1
  # http client
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  # storage
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  # model annotation
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  # routing
  sailor: ^0.7.1
  # internationalization
  intl: ^0.16.1

  # utilities
  supercharged: ^1.5.1
  flutter_bloc: ^4.0.0
  flutter_form_builder: ^3.9.0
  barcode_scan: ^3.0.1
  preferences: ^5.2.0
  jiffy: ^3.0.1

  # ui sugar
  bottom_navy_bar: ^5.4.0
  flutter_vector_icons: ^0.2.1
  flutter_staggered_grid_view: ^0.3.0
  animations: ^1.0.0+5
  modal_bottom_sheet: ^0.1.5
  flutter_spinkit: ^4.1.2+1
  fl_chart: ^0.9.4
  flutter_sticky_header: ^0.4.2
  flushbar: ^1.10.2
  fluttertoast: ^4.0.1
  pull_to_refresh: ^1.5.8

  # log page
  alice: ^0.0.33

  # about page
  package_info: ^0.4.0+18
  qr_flutter: ^3.2.0
  share: ^0.6.4+2
  launch_review: ^2.0.0
  url_launcher: ^5.4.7
  flutter_markdown: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # code generation
  build_runner: ^1.10.0
  # data model & sealed union code generation
  freezed: ^0.10.8
  # generators
  injectable_generator: ^0.3.5
  # toJson/fromJson generator
  json_serializable: ^3.3.0
  # test stubbing
  mockito: ^4.1.1
  # bloc stubs & mocks
  bloc_test: ^5.1.0
  # fast, deterministic, and async timer tests
  fake_async: ^1.1.0
  # icon generation
  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"